
services:
  node_1:
    extends:
      service: ros_docker
      file: ./src/ros_docker/docker-compose.yaml
    build:
      context: ./src/nodes/node_1
    volumes:
      - ./src/nodes/node_1/ros2_ws:/home/ubuntu/ros2_ws
    image: node_1
    container_name: node_1
    hostname: node_1
    depends_on:
      - ros_docker
  
  node_2:
    extends:
      service: ros_docker
      file: ./src/ros_docker/docker-compose.yaml
    build:
      context: ./src/nodes/node_2
    volumes:
      - ./src/nodes/node_2/ros2_ws:/home/ubuntu/ros2_ws
    image: node_2
    container_name: node_2
    hostname: node_2
    depends_on:
      - ros_docker
