#!/usr/bin/env bash

set -e

chown -R ubuntu:ubuntu /home/ubuntu/ros2_ws

cat >> /home/ubuntu/.bashrc << EOF

# Generated by setup.sh! Do not remove!
source /usr/share/colcon_cd/function/colcon_cd.sh
export _colcon_cd_root=~/ros2_ws

EOF

source /home/ubuntu/ros2_ws/install/local_setup.bash
